### ISSUE TITLE
Error in 4.Exercise4.md

### ISSUE THREAD

**Issue by Geonov** [safesoftware/FMETraining#48]
Hi,
I think something is wrong with 4.Exercise4.md :
If you use "count attribute" from Aggregator to count crimes, Blocks with no crime pass through with NumberCrimes = 1 (I think)...
(Because you use a left join so all blocks, even with no crime, pass through Aggregator, so count = 1).

Using "inner join" in FeatureJoiner and connect UnjoinedLeft with a Manager/Creator with NumberCrimes = 0 could be the good answer.

**Comment by Geonov** [comment]
@FMEEvangelist Nobody here ? ^^

**Comment by samuel-walker** [comment]
Hi @Geonov, my apologies, no one was receiving notifications for issues in the repo. I am cleaning them up now. 
You are correct, this should be an inner join. I have fixed it in the [2018](https://github.com/safesoftware/FMETraining/commit/57142c42f91cbbe311d9a427afad78bd4f44811e) and [2019](https://github.com/safesoftware/FMETraining/commit/718f79e4bce016381a3295f00d3087bd13c4c3af) branches. Thanks.
