### ISSUE TITLE
Image with bad name

### ISSUE THREAD

**Issue by Geonov** [safesoftware/FMETraining#61]
/DesktopAdvanced5CustomTransformers/5.Exercise3.md calls for :
(./Images/Img5.222.Ex3.CTWithWeightingTransformers.png)

But in Images directory, we have /Images/Img5.221.Ex3.CTWithWeightingTransformers.png

Img5.221.Ex3.CTWithWeightingTransformers.png should be renamed Img5.222.Ex3.CTWithWeightingTransformers.png

**Comment by samuel-walker** [comment]
This was fixed in 2019, but I have [addressed it in 2018](https://github.com/safesoftware/FMETraining/commit/d1ef82c354678ab1a152d16f60bb208c059daa25) now as well.
