### ISSUE TITLE
Database connection doesn't work

### ISSUE THREAD

**Issue by kingrollo** [safesoftware/FMETraining#62]
The PostGIS database connection described here: https://safe-software.gitbooks.io/fme-desktop-basic-training-2018/content/DesktopBasic5BestPractice/5.Exercise4.html
and here: https://docs.google.com/document/d/1lVBVJWVBnpNLgfpTWpgsZAa-hrv-k_GDp4I16BDGn7M/pub

Seems not to be working?

**Comment by FMEEvangelist** [comment]
Is it still a problem? It's been working fine for me. Perhaps it was just temporarily down, or there is a firewall issue for you?

**Comment by kingrollo** [comment]
@FMEEvangelist, it was suggested to me that it might be something on our local network that's blocking it. Is there a way we can set up a local clone of the database?

**Comment by samuel-walker** [comment]
@kingrollo sorry for the insanely delayed response. I was not receiving notifications for issues.

For anyone running into PostGIS training database issues in the future, [this article](https://community.safe.com/s/article/resetting-the-postgis-training-database) has the details to reset the server. We don't have the option for a local clone if you can't access the database directly. Some of the datasets are also stored in the [FMEData](https://github.com/safesoftware/FMEData/) repo, so you could conceivably host your own database and upload the required datasets.
