### ISSUE TITLE
2 evaluation.json need review

### ISSUE THREAD

**Issue by Geonov** [safesoftware/FMETraining#66]
- evaluation.json for "turn-coordinates-into-geometry/creating-spatial-geometry" is incomplete

- evaluation.json for "design-workspaces-for-advanced-reading-and-writing/exercise-use-partial-runs-to-test-your-workspace" contains a typo error :

```
        "options": [
          "Yes",
          "Bo"
        ],
```
		
=>

```
        "options": [
          "Yes",
          "No"
        ],
```

**Comment by samuel-walker** [comment]
Thanks for pointing this out, @Geonov. `creating-spatial-geometry` and a few other units were renamed and are complete, so I've removed the old incomplete versions. [Commit](https://github.com/safesoftware/FMETraining/commit/474a6aa851f34ab7c618471dcd278a1badde024e ).

The second spelling error issue has been fixed. [Commit](https://github.com/safesoftware/FMETraining/commit/85d5a5562c688e5d80da081843dc8741df056378)
