### ISSUE TITLE
Who is Sven?

### ISSUE THREAD

**Issue by Geonov** [safesoftware/FMETraining#67]
Sven's avatar is missing.

Amar, Fatima, Frank and Jennifer have their avatar, but not Sven.
I suggest to add his avatar picture in "connect-to-data\connect-and-view-data".

**Comment by samuel-walker** [comment]
Thanks for finding this, @Geonov. Sven's avatar has been added. [Commit](https://github.com/safesoftware/FMETraining/commit/2a353cbaa81f6f924b50d333ea8f0ccf7751ab4b)
