### ISSUE TITLE
digital-plan-submission - validate-geometry-following-ogc-standards

### ISSUE THREAD

**Issue by Geonov** [safesoftware/FMETraining#69]
> "using the GeometryFilter and GeometryValidator, Jennifer has identified six geometry validation issues"

I count 8 issues on 3 entities, not 6, right?

![image](https://user-images.githubusercontent.com/25294189/121654006-8ed60900-ca9d-11eb-9739-ae5e533c9146.png)

**Comment by samuel-walker** [comment]
Hi @Geonov. I ran through this and found I had 3 Failed features with only 3 IssueLocations/IssueParts. I'm not sure why our results differ.
![image](https://user-images.githubusercontent.com/31997383/121754546-c0fd6000-cac9-11eb-8e39-512f98cf8b7c.png)

In any case, I updated the text to be a bit more specific.
> By using the GeometryFilter and GeometryValidator, Jennifer has identified four geometry validation issues: one non-line feature and three OGC validation issues. More importantly, she has created a reusable workflow that will reliably identify any such issues in submitted data.
